### ISSUE TITLE
forum.syncthing.net -  "feed" styling

### ISSUE THREAD

**Issue by imsodin** [StylishThemes/Discourse-Dark#32]
- **Link to the site**: https://forum.syncthing.net

The site is not in the known list (https://github.com/StylishThemes/Discourse-Dark/wiki), but the addon gets activated automatically and works perfectly for the most parts (thanks). Except for the "notification feed":

![image](https://user-images.githubusercontent.com/15955093/81918850-554f7780-95d7-11ea-859d-bd9f002653cf.png)

Thanks for a great style!

**Comment by the-j0k3r** [comment]
https://github.com/StylishThemes/Discourse-Dark/wiki is old and likely unmaintained list, so take that list with a pinch (bucket) of salt. User contributions are welcome to mantain that list and wiki in general though. :wink: :+1: 

Since **syncthing** _**IS ALREADY part**_ of the style, I assume you meant to report a bug and not make a feature request, so editing as such.

Expect a fix soon though =)

**Comment by the-j0k3r** [comment]
Heres the problem, because I dont use the style I dont really have notifications to read or duplicate, so this will take a bit longer while I try to find the selectors.

You could help by providing the inspected selectors on browser.

**Comment by imsodin** [comment]
I have expanded the html until the first bright menu entry, I hope that contains the info you need. Otherwise please tell me what else you would like to see. Unfortunately firefox inspector doesn't seem to allow copying the html, so as a screenshot:  
![image](https://user-images.githubusercontent.com/15955093/82023966-5512b300-968f-11ea-996a-52391629a638.png)

**Comment by the-j0k3r** [comment]
>Unfortunately firefox inspector doesn't seem to allow copying the html

It does!

1. Right click on desired area,
1. on menu select copy
1. copy inner or outer html

![Capture](https://user-images.githubusercontent.com/31389848/82032082-09fe9d00-969b-11ea-89dc-9d648ebe0da7.PNG)


However it would be helpful to see the styling being applied.

e.g. something like

![Capture](https://user-images.githubusercontent.com/31389848/82032378-65c92600-969b-11ea-9064-a0e5de0909d8.PNG)

**Comment by imsodin** [comment]
A search for "flash" returns nothing. Filtering styling for `color` returns on the notifications header, which is correctly dark:

![image](https://user-images.githubusercontent.com/15955093/82034239-37007f00-969e-11ea-8d30-d69a122abd2d.png)
![image](https://user-images.githubusercontent.com/15955093/82034272-454e9b00-969e-11ea-8cc5-52cb696980fd.png)

And from the main part that is bright:

![image](https://user-images.githubusercontent.com/15955093/82034327-55ff1100-969e-11ea-901e-e345e4d577e3.png)
![image](https://user-images.githubusercontent.com/15955093/82034417-6dd69500-969e-11ea-91e0-658e2b905ea9.png)

(These screenshots make me realize I probably need a userstyle for devtools :) ).

**Comment by the-j0k3r** [comment]
`.flash` was an example hence its started with e.g. and its GitHub only.

**Comment by imsodin** [comment]
Firstly: Will this effort only be worth something on forum.syncthing.net or potentially benefit others too? If it's syncthing only, I don't want to use so much of your time, as this will only have very limited users (maybe just me). Please tell me and skip all the rest if that's the case.

That snippet affects all entries except the unreads one (which don't have the .read class) and makes the usernames unreadable: 
![image](https://user-images.githubusercontent.com/15955093/82036380-230a4c80-96a1-11ea-91b2-c84b0d2c3895.png)
The unread ones don't have a class at all, I can make them affected with the selector `.user-menu .quick-access-panel li` (without the `li` it doesn't apply).

Username is a span without class:

```
<a href="/t/database-migration-1-6-0-rc2/15006/5" title="mentioned" data-auto-route="true"><svg class="fa d-icon d-icon-at svg-icon svg-node" aria-hidden="true"><use xlink:href="#at"></use></svg><div><span>rustycanb</span> <span data-topic-id="15006">Database migration 1.6.0~rc2</span></div></a>
```
and has these rules

```
.user-menu .quick-access-panel li span:first-child {
	color: #222;
}
```
```
.user-menu .quick-access-panel li a > div {
	overflow-wrap: anywhere;
}
```
plus stuff inherited from `a` and `body`, guess that's not relevant?

**Comment by the-j0k3r** [comment]
> Firstly: Will this effort only be worth something on forum.syncthing.net or potentially benefit others too?

I think other will too, no way of testing without joining other sites

>and has these rules
>
```
.user-menu .quick-access-panel li span:first-child {
	color: #222;
}
```
>
```
.user-menu .quick-access-panel li a > div {
	overflow-wrap: anywhere;
}
```

OK we are looking for the blue background property which is not there, also were only interested in rules that have background, color, border/style/color, things like overflow props ideally we dont want to apply properties that dont exist in default.

I'll try to find the stylesheet that has these entries and work from there based on the class names you gave, it will be easier to ID which belong here.

Thanks.

**Comment by the-j0k3r** [comment]
OK can you test these

```css
	.user-menu .quick-access-panel .read {
		background: #111;
	}
	div.menu-links-header .menu-links-row {
		border-color: #444;
	}
	div.menu-links-header .menu-links-row li a.active, div.menu-links-header .menu-links-row li a.active:after {
		border-color: #555;
	}
	.user-menu .quick-access-panel .show-all a:hover {
		color: #ddd;
		background: #282828
	}
	div.menu-links-header a:hover, div.menu-links-header a:focus {
		background-color: #182030;
	}
	.user-menu .quick-access-panel .show-all a {
		color: #ccc;
		background: #222;
	}
	div.menu-links-header .fa, div.menu-links-header a {
		color: #ccc;
	}
```
